FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
COPY MyTelegramBot/* ./src/MyTelegramBot/
COPY MongoDatabase/* ./src/MongoDatabase/
WORKDIR /src/MyTelegramBot

RUN dotnet build -o /app
FROM build as publish
RUN dotnet publish -o /publish


FROM base as final
COPY --from=publish /publish /app
WORKDIR /app
ENTRYPOINT ["dotnet", "MyTelegramBot.dll"] 
