version: "3.3"

volumes: 
  mongodb_volume:
services:
  bot:
    container_name: bot
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.MyTelegramBot
    environment:
      BotToken: "6387702271:AAFzX7YdmVEGFcrA4X1pceHLEQHhTrg4xqY"
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      connectionString: "mongodb://mongodb:27017" 
      providerToken: "381764678:TEST:61989"
      api_hash: "e12dcc19eff5b203886362fbe196e9d4"
      api_id: "26157385"
      phone_number: "+79261025100"
      pathToMaterials: "/root/TelegramBot/Materials/"
    ports: 
      - "8080:8080"
    depends_on: 
      - mongodb 
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    #restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_volume:/data/db
